# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
