# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build /P:SourceLinkCreate=false --configuration $(buildConfiguration)
  displayName: Build

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: "**/*Tests/*.csproj"
    arguments: '/P:SourceLinkCreate=false --configuration $(buildConfiguration) --collect "Code coverage"'

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts